# Generated by Django 5.2.7 on 2025-11-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_order_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_order_created_at_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='orders_payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='orders_payment_created_at_idx',
        ),
    ]
