# Generated by Django 5.1 on 2025-11-27 10:32

from django.db import migrations


def rename_payment_status(apps, schema_editor):
    """Update all Payment records from SUCCESS to COMPLETED"""
    Payment = apps.get_model('orders', 'Payment')
    Payment.objects.filter(status='SUCCESS').update(status='COMPLETED')


def reverse_rename_payment_status(apps, schema_editor):
    """Reverse migration: Update all Payment records from COMPLETED back to SUCCESS"""
    Payment = apps.get_model('orders', 'Payment')
    Payment.objects.filter(status='COMPLETED').update(status='SUCCESS')


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_is_archived"),
    ]

    operations = [
        migrations.RunPython(rename_payment_status, reverse_rename_payment_status),
    ]
