# Generated by Django 5.1 on 2025-11-27 15:07

from django.db import migrations, models


def update_in_progress_to_finished(apps, schema_editor):
    """Update all IN_PROGRESS orders to FINISHED status"""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='IN_PROGRESS').update(status='FINISHED')


def reverse_finished_to_in_progress(apps, schema_editor):
    """Reverse migration - not recommended but included for completeness"""
    # This is a no-op since we can't reliably determine which FINISHED orders
    # were originally IN_PROGRESS
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status_alter_payment_method_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_in_progress_to_finished,
            reverse_finished_to_in_progress
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('PENDING', 'Pending'),
                    ('FINISHED', 'Finished'),
                    ('CANCELLED', 'Cancelled'),
                    ('EXPIRED', 'Expired'),
                    ('REFUNDED', 'Refunded'),
                ],
                default='PENDING'
            ),
        ),
    ]
