# Generated by Django 4.2.13 on 2025-12-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("ARCHIVE", "Archive"),
                            ("RESTORE", "Restore"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("record_id", models.IntegerField(db_index=True)),
                ("description", models.TextField(blank=True)),
                (
                    "data_before",
                    models.JSONField(
                        blank=True,
                        help_text="State before the change (for UPDATE/DELETE)",
                        null=True,
                    ),
                ),
                (
                    "data_after",
                    models.JSONField(
                        blank=True,
                        help_text="State after the change (for CREATE/UPDATE)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="system_audi_user_id_cb8465_idx",
                    ),
                    models.Index(
                        fields=["model_name", "created_at"],
                        name="system_audi_model_n_b0def9_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="system_audi_action_a620c5_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="system_audi_content_c99aa4_idx",
                    ),
                ],
            },
        ),
    ]
