"""
Django settings for sales_inventory project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (located in project root)
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(PROJECT_ROOT / ".env")

# Unified DEBUG flag (case-insensitive env)
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY: SECRET_KEY must be set in environment - no insecure default for production
if DEBUG:
    # Local development only - insecure default
    SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-dev-key-not-for-production")
else:
    # Production - must have SECRET_KEY set in environment
    SECRET_KEY = os.getenv("SECRET_KEY")
    if not SECRET_KEY:
        raise ValueError(
            "SECRET_KEY environment variable is not set. "
            "Set it in Render environment variables or local .env file."
        )

# Parse ALLOWED_HOSTS - detect Render environment and use appropriate domain
if os.getenv("RENDER"):
    # Running on Render - extract domain from RENDER_EXTERNAL_URL (set automatically by Render)
    if os.getenv("RENDER_EXTERNAL_URL"):
        render_url = os.getenv("RENDER_EXTERNAL_URL")
        render_domain = render_url.split("//")[1] if "//" in render_url else render_url
        # Production: only allow the actual Render domain, no localhost
        ALLOWED_HOSTS = [render_domain]
    else:
        # Fallback if RENDER_EXTERNAL_URL somehow not available
        raise ValueError(
            "RENDER_EXTERNAL_URL environment variable is not set. "
            "Render should set this automatically."
        )
else:
    # Local development - read from environment or use defaults
    _allowed_hosts = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom apps
    "sales_inventory_system.accounts",
    "sales_inventory_system.products",
    "sales_inventory_system.orders",
    "sales_inventory_system.analytics",
    "sales_inventory_system.system",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # must be above others
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sales_inventory_system.system.middleware.AuditMiddleware",
]

ROOT_URLCONF = "sales_inventory_system.sales_inventory.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                "sales_inventory_system.products.context_processors.low_stock_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "sales_inventory.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Database configuration - default to SQLite locally, allow DATABASE_URL/engine override
DB_CONN_MAX_AGE = int(os.getenv("DB_CONN_MAX_AGE", "600"))
DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.sqlite3")
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL and DB_ENGINE == "django.db.backends.sqlite3":
    sqlite_name = os.getenv("DB_NAME", "db.sqlite3")
    sqlite_path = Path(sqlite_name)
    if not sqlite_path.is_absolute():
        sqlite_path = BASE_DIR / sqlite_path

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_path,
        }
    }
elif DATABASE_URL:
    is_sqlite_url = DATABASE_URL.startswith("sqlite")
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0 if is_sqlite_url else DB_CONN_MAX_AGE,
            conn_health_checks=not is_sqlite_url,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": os.getenv("DB_NAME", "fcj_pizza"),
            "USER": os.getenv("DB_USER", "fcj_pizza_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            # Connection pooling settings for better performance (non-SQLite)
            "CONN_MAX_AGE": DB_CONN_MAX_AGE,
            "OPTIONS": {
                "connect_timeout": 10,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
    WHITENOISE_USE_FINDERS = True  # allow serving from STATICFILES_DIRS without collectstatic
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login URLs
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "accounts:login"

# Caching configuration
CACHES = {
    "default": {
        "BACKEND": os.getenv("CACHE_BACKEND", "django.core.cache.backends.locmem.LocMemCache"),
        "LOCATION": os.getenv("CACHE_LOCATION", "fcp-cache"),
        "TIMEOUT": int(os.getenv("CACHE_TIMEOUT", "300")),  # 5 minutes default
        "OPTIONS": {
            "MAX_ENTRIES": int(os.getenv("CACHE_MAX_ENTRIES", "1000")),
        }
    }
}

# Logging configuration for performance monitoring
# Use console-only logging to work in production environments like Render
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# Performance optimizations
# Session timeout (in seconds)
SESSION_COOKIE_AGE = 3600 * 24 * 7  # 1 week
# Use database sessions for distributed deployments
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Template caching
if not DEBUG:
    TEMPLATES[0]["OPTIONS"]["loaders"] = [
        ("django.template.loaders.cached.Loader", [
            "django.template.loaders.filesystem.Loader",
            "django.template.loaders.app_directories.Loader",
        ]),
    ]
