# Generated by Django 5.2.7 on 2025-11-19 03:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pcs', 'Pieces'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons')], help_text='Unit of measurement', max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level before alert', max_digits=10)),
                ('variance_allowance', models.DecimalField(decimal_places=2, default=10, help_text='Variance allowance percentage (e.g., 10% for portioning tolerance)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_quantity', models.DecimalField(decimal_places=3, help_text='Actual quantity counted', max_digits=10)),
                ('theoretical_quantity', models.DecimalField(decimal_places=3, help_text='Quantity according to system records', max_digits=10)),
                ('count_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='PrepBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Dough Prep Batch 001'", max_length=200)),
                ('quantity_produced', models.IntegerField(help_text='Number of products created')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('prep_start', models.DateTimeField(blank=True, null=True)),
                ('prep_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('DEDUCTION', 'Deduction (Sale)'), ('ADJUSTMENT', 'Adjustment'), ('WASTE', 'Waste/Spoilage'), ('FREEBIE', 'Freebie/Giveaway'), ('PREP', 'Prep Batch Conversion')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_type', models.CharField(blank=True, help_text="e.g., 'order', 'physical_count', 'waste_log', 'prep_batch'", max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VarianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('theoretical_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('actual_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('variance_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('variance_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('within_tolerance', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('SPOILAGE', 'Spoilage'), ('WASTE', 'Waste'), ('FREEBIE', 'Freebie/Giveaway'), ('SAMPLE', 'Sample'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.TextField(help_text='Description of why item was wasted')),
                ('waste_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-waste_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_product_is_archived_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_product_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_product_category_archived_idx',
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='counted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalcount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='prepbatch',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='product',
            field=models.OneToOneField(help_text='Product that this recipe creates', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='products.product'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.recipeitem'),
        ),
        migrations.AddField(
            model_name='prepbatch',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_batches', to='products.recipeitem'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variancerecord',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_records', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['ingredient', 'created_at'], name='products_st_ingredi_060ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='variancerecord',
            index=models.Index(fields=['ingredient', 'period_end'], name='products_va_ingredi_31cc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['ingredient', 'waste_date'], name='products_wa_ingredi_a4d3f5_idx'),
        ),
    ]
