# Generated by Django 5.2.8 on 2025-11-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_ingredient_physicalcount_prepbatch_recipeingredient_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Temporarily toggleable by cashier (false = out of stock/unavailable)",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("l", "Liters"),
                    ("pcs", "Pieces"),
                    ("cup", "Cups"),
                    ("tbsp", "Tablespoons"),
                    ("tsp", "Teaspoons"),
                ],
                default="g",
                help_text="Unit of measurement",
                max_length=50,
            ),
        ),
    ]
