# Generated by Django 5.2.8 on 2025-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_ingredient_is_available_alter_ingredient_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="cost_per_unit",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[("g", "Grams"), ("ml", "Milliliters"), ("pcs", "Pieces")],
                default="g",
                help_text="Unit of measurement",
                max_length=50,
            ),
        ),
    ]
