# Generated by Django 5.2.8 on 2025-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_ingredient_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="requires_bom",
            field=models.BooleanField(
                default=False,
                help_text="If True, this product requires a Bill of Materials (BOM). If False, it's a simple stock item.",
            ),
        ),
    ]
